import { EntryTypeDefinition } from '@acme/shared';

export enum PsychiatryEntryType {
  CLINICAL_CASE_REVIEW = 'CLINICAL_CASE_REVIEW',
  CASE_BASED_DISCUSSION = 'CASE_BASED_DISCUSSION',
  SIGNIFICANT_EVENT = 'SIGNIFICANT_EVENT',
  REFLECTIVE_PRACTICE = 'REFLECTIVE_PRACTICE',
  PSYCHOTHERAPY_CASE = 'PSYCHOTHERAPY_CASE',
  DONCS = 'DONCS',
  MHA_APPLICATION = 'MHA_APPLICATION',
  TEACHING_ACTIVITY = 'TEACHING_ACTIVITY',
  QI_PROJECT = 'QI_PROJECT',
  FEEDBACK_REFLECTION = 'FEEDBACK_REFLECTION',
}

export const PSYCHIATRY_ENTRY_TYPES: EntryTypeDefinition[] = [
  {
    code: PsychiatryEntryType.CLINICAL_CASE_REVIEW,
    label: 'Clinical Case Review (ACE)',
    description:
      'Reflection on a psychiatric assessment personally conducted. The core entry type for clinical encounters including history, MSE, formulation, risk assessment, and management plan.',
    templateId: 'PSY_ACE_TEMPLATE',
    classificationSignals: [
      'patient assessment',
      'mental state examination',
      'MSE',
      'psychiatric history',
      'formulation',
      'risk assessment',
      'diagnosis',
      'management plan',
      'prescribed',
      'admission',
      'discharge',
      'ward round',
      'clinic',
      'community visit',
      'crisis assessment',
    ],
    frequency: '6 per year (at least 1 per placement)',
  },
  {
    code: PsychiatryEntryType.CASE_BASED_DISCUSSION,
    label: 'Case-Based Discussion (CbD)',
    description:
      'Structured discussion of a case with a supervisor focusing on clinical reasoning, risk management, ethical considerations, and application of the Mental Health Act.',
    templateId: 'PSY_CBD_TEMPLATE',
    classificationSignals: [
      'discussed with supervisor',
      'case discussion',
      'clinical reasoning',
      'differential diagnosis',
      'formulation discussed',
      'CbD',
      'case-based discussion',
      'supervisor meeting',
      'reviewed with consultant',
    ],
    frequency: '4 per year (at least 1 per placement)',
  },
  {
    code: PsychiatryEntryType.SIGNIFICANT_EVENT,
    label: 'Significant Event Analysis',
    description:
      'Analysis of a significant event such as patient suicide, serious self-harm, safeguarding concern, restraint incident, or near-miss. Focus on root cause and systemic learning.',
    templateId: 'PSY_SEA_TEMPLATE',
    classificationSignals: [
      'suicide',
      'completed suicide',
      'serious self-harm',
      'death',
      'restraint',
      'seclusion',
      'abscond',
      'serious incident',
      'safeguarding',
      'complaint',
      'near-miss',
      'unexpected outcome',
      'patient safety',
      'never event',
      'serious untoward incident',
      'SUI',
    ],
    frequency: 'At least 1 per year',
  },
  {
    code: PsychiatryEntryType.REFLECTIVE_PRACTICE,
    label: 'Reflective Practice Entry',
    description:
      'General reflection on a clinical or professional experience. Broader than a case review, suited to exploring emotional impact, professional development, and the therapeutic relationship.',
    templateId: 'PSY_REFLECTION_TEMPLATE',
    classificationSignals: [
      'reflection',
      'thought about',
      'made me think',
      'emotional impact',
      'Balint group',
      'supervision discussion',
      'professional development',
      'therapeutic relationship',
      'countertransference',
      'learning moment',
      'interesting situation',
      'ethical dilemma',
    ],
    frequency: 'Regular throughout training',
  },
  {
    code: PsychiatryEntryType.PSYCHOTHERAPY_CASE,
    label: 'Psychotherapy Case Reflection (SAPE)',
    description:
      'Reflection on psychotherapy delivered under supervision. Covers therapeutic modality, process, formulation, transference/countertransference, and outcomes. Required: minimum two modalities during core training.',
    templateId: 'PSY_SAPE_TEMPLATE',
    classificationSignals: [
      'psychotherapy',
      'CBT',
      'cognitive behavioural',
      'psychodynamic',
      'CAT',
      'cognitive analytic',
      'DBT',
      'dialectical',
      'family therapy',
      'systemic therapy',
      'therapeutic session',
      'therapy case',
      'transference',
      'countertransference',
      'formulation',
      'therapeutic alliance',
      'SAPE',
    ],
    frequency: 'Minimum 2 modalities during core training',
  },
  {
    code: PsychiatryEntryType.DONCS,
    label: 'Direct Observation of Non-Clinical Skills (DONCS)',
    description:
      'Reflection on observed non-clinical skills such as chairing an MDT meeting, family meeting facilitation, teaching delivery, or inter-agency liaison.',
    templateId: 'PSY_DONCS_TEMPLATE',
    classificationSignals: [
      'MDT meeting',
      'ward round presentation',
      'family meeting',
      'CPA meeting',
      'care programme approach',
      'tribunal',
      'managers hearing',
      'teaching session',
      'presenting to team',
      'chairing',
      'inter-agency',
      'DONCS',
    ],
    frequency: '2 per year',
  },
  {
    code: PsychiatryEntryType.MHA_APPLICATION,
    label: 'Mental Health Act Application',
    description:
      'Reflection on use of mental health legislation including detention, capacity assessment, community treatment orders, or emergency powers. Covers legal reasoning, human rights balancing, and ethical considerations.',
    templateId: 'PSY_MHA_TEMPLATE',
    classificationSignals: [
      'Mental Health Act',
      'MHA',
      'Section 2',
      'Section 3',
      'Section 5',
      'Section 136',
      'Section 117',
      'detained',
      'sectioned',
      'compulsory treatment',
      'CTO',
      'community treatment order',
      'capacity',
      'best interests',
      'DoLS',
      'tribunal',
      'nearest relative',
      'AMHP',
    ],
    frequency: 'When applicable (at least 2 during training)',
  },
  {
    code: PsychiatryEntryType.TEACHING_ACTIVITY,
    label: 'Teaching & Education Activity',
    description:
      'Reflection on planning and delivering teaching, or supervising junior colleagues. Covers teaching methods, feedback received, and impact on learners.',
    templateId: 'PSY_TEACHING_TEMPLATE',
    classificationSignals: [
      'teaching',
      'taught',
      'lecture',
      'seminar',
      'presentation',
      'training session',
      'supervising',
      'mentoring',
      'journal club',
      'case conference',
      'grand round',
      'medical student',
      'nursing student',
    ],
    frequency: 'At least 1 per year',
  },
  {
    code: PsychiatryEntryType.QI_PROJECT,
    label: 'Quality Improvement Project',
    description:
      'A structured quality improvement project within a psychiatric service, with PDSA cycles, data collection, and sustainability plan.',
    templateId: 'PSY_QIP_TEMPLATE',
    classificationSignals: [
      'audit',
      'quality improvement',
      'QI project',
      'PDSA',
      'data collection',
      'service improvement',
      'clinical governance',
      'protocol change',
      'baseline measurement',
      're-audit',
    ],
    frequency: 'At least 1 during training',
  },
  {
    code: PsychiatryEntryType.FEEDBACK_REFLECTION,
    label: 'Reflection on Feedback (MSF)',
    description:
      'Reflection on multi-source feedback (MSF), patient feedback, exam results (MRCPsych), or supervisor feedback.',
    templateId: 'PSY_FEEDBACK_TEMPLATE',
    classificationSignals: [
      'MSF',
      'multi-source feedback',
      'patient feedback',
      'exam results',
      'MRCPsych',
      'feedback',
      'appraisal',
      'supervisor feedback',
      'colleague feedback',
      'ratings',
      'scores',
    ],
    frequency: 'After each feedback cycle',
  },
];
