import { EntryTypeDefinition } from '@acme/shared';

export enum ImEntryType {
  CLINICAL_CASE_REVIEW = 'CLINICAL_CASE_REVIEW',
  CASE_BASED_DISCUSSION = 'CASE_BASED_DISCUSSION',
  ACUTE_CARE_ASSESSMENT = 'ACUTE_CARE_ASSESSMENT',
  SIGNIFICANT_EVENT = 'SIGNIFICANT_EVENT',
  REFLECTIVE_PRACTICE = 'REFLECTIVE_PRACTICE',
  PROCEDURAL_SKILLS = 'PROCEDURAL_SKILLS',
  OUTPATIENT_ASSESSMENT = 'OUTPATIENT_ASSESSMENT',
  TEACHING_ACTIVITY = 'TEACHING_ACTIVITY',
  QI_PROJECT = 'QI_PROJECT',
  FEEDBACK_REFLECTION = 'FEEDBACK_REFLECTION',
}

export const IM_ENTRY_TYPES: EntryTypeDefinition[] = [
  {
    code: ImEntryType.CLINICAL_CASE_REVIEW,
    label: 'Clinical Case Review (Mini-CEX)',
    description:
      'Reflection on a clinical encounter personally assessed. The core entry type for bedside assessments covering history, examination, clinical reasoning, and management.',
    templateId: 'IM_MINIEX_TEMPLATE',
    classificationSignals: [
      'patient assessment',
      'history taking',
      'clinical examination',
      'diagnosis',
      'management plan',
      'prescribed',
      'ward round',
      'clinic',
      'admitted',
      'discharged',
      'clerked',
      'post-take',
      'on-call',
    ],
    frequency: '6 per year',
  },
  {
    code: ImEntryType.CASE_BASED_DISCUSSION,
    label: 'Case-Based Discussion (CbD)',
    description:
      'Structured discussion of a case with a supervisor focusing on clinical reasoning, diagnostic uncertainty, management of comorbidities, and evidence-based decision-making.',
    templateId: 'IM_CBD_TEMPLATE',
    classificationSignals: [
      'discussed with consultant',
      'case discussion',
      'clinical reasoning',
      'differential diagnosis',
      'CbD',
      'case-based discussion',
      'supervisor meeting',
      'reviewed with consultant',
      'post-take discussion',
    ],
    frequency: '4 per year',
  },
  {
    code: ImEntryType.ACUTE_CARE_ASSESSMENT,
    label: 'Acute Care Assessment (ACAT)',
    description:
      'Reflection on management of an acute unselected or specialty take, or the care of an acutely deteriorating patient. Covers the full episode from presentation through to disposition.',
    templateId: 'IM_ACAT_TEMPLATE',
    classificationSignals: [
      'acute take',
      'unselected take',
      'on-call',
      'acute admission',
      'deteriorating patient',
      'resuscitation',
      'crash call',
      'MET call',
      'NEWS score',
      'escalation',
      'ACAT',
      'acute assessment',
      'handover',
    ],
    frequency: '4 per year',
  },
  {
    code: ImEntryType.SIGNIFICANT_EVENT,
    label: 'Significant Event Analysis',
    description:
      'Analysis of a significant event such as a patient safety incident, unexpected deterioration, cardiac arrest, near-miss, or complaint. Focus on root cause and systemic learning.',
    templateId: 'IM_SEA_TEMPLATE',
    classificationSignals: [
      'patient safety',
      'serious incident',
      'near-miss',
      'cardiac arrest',
      'unexpected death',
      'complaint',
      'never event',
      'duty of candour',
      'Datix',
      'incident report',
      'mortality review',
    ],
    frequency: 'At least 1 per year',
  },
  {
    code: ImEntryType.REFLECTIVE_PRACTICE,
    label: 'Reflective Practice Entry',
    description:
      'General reflection on a clinical or professional experience. Suited to exploring diagnostic uncertainty, ethical dilemmas, communication challenges, or personal development.',
    templateId: 'IM_REFLECTION_TEMPLATE',
    classificationSignals: [
      'reflection',
      'thought about',
      'made me think',
      'learning moment',
      'interesting case',
      'ethical dilemma',
      'communication challenge',
      'uncertainty',
      'difficult conversation',
      'end of life',
    ],
    frequency: 'Regular throughout training',
  },
  {
    code: ImEntryType.PROCEDURAL_SKILLS,
    label: 'Procedural Skills (DOPS)',
    description:
      'Reflection on performing or observing a practical procedure. Covers indication, consent, technique, complications, and supervision level.',
    templateId: 'IM_DOPS_TEMPLATE',
    classificationSignals: [
      'procedure',
      'DOPS',
      'lumbar puncture',
      'chest drain',
      'central line',
      'ascitic tap',
      'paracentesis',
      'pleural aspiration',
      'NG tube',
      'DC cardioversion',
      'arterial blood gas',
      'cannulation',
    ],
    frequency: 'As required for procedural competencies',
  },
  {
    code: ImEntryType.OUTPATIENT_ASSESSMENT,
    label: 'Outpatient Care Assessment (OPCAT)',
    description:
      'Reflection on managing patients in an outpatient, ambulatory, or community setting. Covers long-term condition management, clinic letters, and shared decision-making.',
    templateId: 'IM_OPCAT_TEMPLATE',
    classificationSignals: [
      'outpatient',
      'clinic',
      'follow-up',
      'long-term condition',
      'ambulatory',
      'community',
      'virtual clinic',
      'clinic letter',
      'OPCAT',
      'new patient',
      'review appointment',
    ],
    frequency: '2 per year',
  },
  {
    code: ImEntryType.TEACHING_ACTIVITY,
    label: 'Teaching & Supervision Activity',
    description:
      'Reflection on planning and delivering teaching, or supervising junior colleagues. Covers teaching methods, feedback received, and impact on learners.',
    templateId: 'IM_TEACHING_TEMPLATE',
    classificationSignals: [
      'teaching',
      'taught',
      'lecture',
      'bedside teaching',
      'simulation',
      'supervising',
      'FY1',
      'medical student',
      'grand round',
      'journal club',
      'case presentation',
    ],
    frequency: 'At least 1 per year',
  },
  {
    code: ImEntryType.QI_PROJECT,
    label: 'Quality Improvement Project (QIPAT)',
    description:
      'A structured quality improvement project with PDSA cycles, data collection, and sustainability plan within a medical service.',
    templateId: 'IM_QIP_TEMPLATE',
    classificationSignals: [
      'audit',
      'quality improvement',
      'QI project',
      'PDSA',
      'QIPAT',
      'data collection',
      'service improvement',
      'clinical governance',
      'protocol change',
      're-audit',
    ],
    frequency: 'At least 1 during training',
  },
  {
    code: ImEntryType.FEEDBACK_REFLECTION,
    label: 'Reflection on Feedback (MSF)',
    description:
      'Reflection on multi-source feedback (MSF), patient survey (PS), MRCP exam results, or supervisor feedback.',
    templateId: 'IM_FEEDBACK_TEMPLATE',
    classificationSignals: [
      'MSF',
      'multi-source feedback',
      'patient survey',
      'MRCP',
      'exam results',
      'feedback',
      'appraisal',
      'supervisor feedback',
      'colleague feedback',
      'MCR',
      'multiple consultant report',
    ],
    frequency: 'After each feedback cycle',
  },
];
