import { interrupt } from '@langchain/langgraph';
import { Logger } from '@nestjs/common';
import { ANALYSIS_STEP_STARTED, GraphDeps } from '../graph-deps';
import { PortfolioStateType } from '../portfolio-graph.state';

const logger = new Logger('AskFollowupNode');

/**
 * Factory that creates the ask_followup node with injected dependencies.
 *
 * This node is interrupt-only — it reads the questions generated by the
 * preceding generate_followup node from state, then pauses the graph
 * via interrupt(). No LLM calls are made here, so the interrupt replay
 * on resume is cheap (just a state read).
 *
 * On resume, the graph loops back to gather_context → check_completeness.
 */
export function createAskFollowupNode(deps: GraphDeps) {
  return async function askFollowupNode(
    state: PortfolioStateType
  ): Promise<Partial<PortfolioStateType>> {
    const cid = state.conversationId;
    deps.eventEmitter.emit(ANALYSIS_STEP_STARTED, {
      conversationId: cid,
      step: 'ask_followup',
    });
    logger.log(
      `[${cid}] Presenting follow-up questions (round ${state.followUpRound}, ` +
        `${state.pendingFollowupQuestions.length} questions)`
    );

    // ── Pause the graph — service layer will create the ASSISTANT message ──
    // On first execution: interrupt() throws, pausing the graph.
    // On resume: interrupt() returns the resume value (true) immediately.
    // No LLM call here — generate_followup already did that and it's checkpointed.
    interrupt({
      type: 'followup',
      questions: state.pendingFollowupQuestions,
      missingSections: state.missingSections,
      entryType: state.entryType,
      followUpRound: state.followUpRound,
    });

    return {};
  };
}
