import { EntryTypeDefinition } from '@acme/shared';

export enum GpEntryType {
  CLINICAL_CASE_REVIEW = 'CLINICAL_CASE_REVIEW',
  SIGNIFICANT_EVENT = 'SIGNIFICANT_EVENT',
  LEARNING_EVENT = 'LEARNING_EVENT',
  FEEDBACK_REFLECTION = 'FEEDBACK_REFLECTION',
  LEADERSHIP_ACTIVITY = 'LEADERSHIP_ACTIVITY',
  ACADEMIC_ACTIVITY = 'ACADEMIC_ACTIVITY',
  OUT_OF_HOURS = 'OUT_OF_HOURS',
  QI_PROJECT = 'QI_PROJECT',
  QI_ACTIVITY = 'QI_ACTIVITY',
  PRESCRIBING = 'PRESCRIBING',
}

export const GP_ENTRY_TYPES: EntryTypeDefinition[] = [
  {
    code: GpEntryType.CLINICAL_CASE_REVIEW,
    label: 'Clinical Case Review',
    description:
      'Reflection on a patient case personally seen. The core learning log entry for clinical encounters.',
    templateId: 'CCR_TEMPLATE',
    classificationSignals: [
      'specific patient',
      'clinical details',
      'diagnosis',
      'management plan',
      'examination findings',
      'prescribed',
      'referred',
      'investigation results',
      'no adverse event',
    ],
    frequency: '36 per year (3 per month)',
  },
  {
    code: GpEntryType.SIGNIFICANT_EVENT,
    label: 'Significant Event Analysis',
    description:
      'Analysis of an event that met the GMC threshold for harm. Focus on root cause and systemic change.',
    templateId: 'SEA_TEMPLATE',
    classificationSignals: [
      'harm',
      'near-miss',
      'complaint',
      'unexpected outcome',
      'patient safety',
      'error',
      'adverse event',
      'deterioration',
      'death',
      'serious incident',
      'GMC threshold',
    ],
    frequency: 'At least 1 per 6 months',
  },
  {
    code: GpEntryType.LEARNING_EVENT,
    label: 'Learning Event Analysis',
    description:
      'Analysis of an event that presented a learning opportunity but did not cause GMC-threshold harm.',
    templateId: 'LEA_TEMPLATE',
    classificationSignals: [
      'learning opportunity',
      'no harm occurred',
      'could have gone wrong',
      'improvement potential',
      'good practice observed',
      'interesting case',
      'unusual presentation',
    ],
    frequency: 'At least 1 per year',
  },
  {
    code: GpEntryType.FEEDBACK_REFLECTION,
    label: 'Reflection on Feedback',
    description:
      'Reflection on feedback received from colleagues (MSF), patients (PSQ), or exam results.',
    templateId: 'FEEDBACK_TEMPLATE',
    classificationSignals: [
      'MSF',
      'multi-source feedback',
      'PSQ',
      'patient satisfaction',
      'exam results',
      'feedback',
      'survey',
      'colleague feedback',
      'appraisal',
      'scores',
      'ratings',
    ],
    frequency: 'After each feedback cycle',
  },
  {
    code: GpEntryType.LEADERSHIP_ACTIVITY,
    label: 'Leadership Activity',
    description:
      'Reflective entry on a leadership, management, or organisational activity undertaken.',
    templateId: 'LEADERSHIP_TEMPLATE',
    classificationSignals: [
      'chairing',
      'presenting',
      'managing',
      'supervising',
      'team conflict',
      'organisational change',
      'led a meeting',
      'coordinated',
      'protocol development',
      'wellbeing initiative',
    ],
    frequency: 'Required in ST3',
  },
  {
    code: GpEntryType.ACADEMIC_ACTIVITY,
    label: 'Academic Activity',
    description:
      'Reflection on an academic activity such as research, teaching, journal club, or literature review.',
    templateId: 'LEA_TEMPLATE',
    classificationSignals: [
      'research',
      'teaching',
      'academic presentation',
      'journal club',
      'literature review',
      'published',
      'abstract',
      'poster',
      'lecture',
    ],
    frequency: 'When applicable (academic trainees)',
  },
  {
    code: GpEntryType.OUT_OF_HOURS,
    label: 'Out of Hours / Urgent Care',
    description:
      'Reflection on cases seen during out-of-hours or unscheduled urgent care sessions.',
    templateId: 'CCR_TEMPLATE',
    classificationSignals: [
      'on call',
      'OOH',
      'out of hours',
      'urgent care',
      'unscheduled',
      'overnight',
      'duty doctor',
      'walk-in',
      'emergency',
    ],
    frequency: 'When applicable',
  },
  {
    code: GpEntryType.QI_PROJECT,
    label: 'Quality Improvement Project',
    description:
      'A structured quality improvement project with PDSA cycles, data collection, and sustainability plan.',
    templateId: 'QIP_TEMPLATE',
    classificationSignals: [
      'audit cycle',
      'PDSA',
      'quality improvement project',
      'data collection',
      'run chart',
      'baseline measurement',
      'protocol change',
      'practice-wide',
      'sustainability',
    ],
    frequency: 'At least 1 during primary care placements',
  },
  {
    code: GpEntryType.QI_ACTIVITY,
    label: 'Quality Improvement Activity',
    description:
      'A smaller-scale quality improvement activity demonstrating ability to identify and act on quality issues.',
    templateId: 'QIA_TEMPLATE',
    classificationSignals: [
      'small improvement',
      'single audit',
      'brief evaluation',
      'practice-level change',
      'quality improvement activity',
      'identified a gap',
      'implemented a change',
    ],
    frequency: 'At least 1 per year',
  },
  {
    code: GpEntryType.PRESCRIBING,
    label: 'Prescribing Assessment',
    description:
      'Reflection on prescribing practice based on a review of prescriptions against GP prescribing proficiencies.',
    templateId: 'PRESCRIBING_TEMPLATE',
    classificationSignals: [
      'prescribing patterns',
      'medication review',
      'formulary',
      'polypharmacy',
      'drug interactions',
      'prescribing errors',
      'BNF',
      'antimicrobial stewardship',
      '50 prescriptions',
      'prescribing proficiencies',
    ],
    frequency: 'Required in ST3',
  },
];
