export enum MessageMetadataType {
  // Presentation (ASSISTANT messages)
  CLASSIFICATION_OPTIONS = 100,
  FOLLOWUP_QUESTIONS = 200,
  CAPABILITY_OPTIONS = 300,

  // Audit (SYSTEM messages)
  CLASSIFICATION_SELECTION = 400,
  CAPABILITY_SELECTION = 500,
}
