/**
 * Medical keyterms for AssemblyAI Universal-3 Pro
 * Improves transcription accuracy for domain-specific vocabulary
 * Max 1,000 terms, each max 6 words
 */
export const MEDICAL_KEYTERMS: string[] = [
  // Common UK medications
  'Metformin',
  'Ramipril',
  'Amlodipine',
  'Omeprazole',
  'Lansoprazole',
  'Atorvastatin',
  'Simvastatin',
  'Levothyroxine',
  'Salbutamol',
  'Beclometasone',
  'Sertraline',
  'Citalopram',
  'Amitriptyline',
  'Gabapentin',
  'Pregabalin',
  'Codeine',
  'Tramadol',
  'Naproxen',
  'Ibuprofen',
  'Paracetamol',
  'Aspirin',
  'Clopidogrel',
  'Warfarin',
  'Apixaban',
  'Rivaroxaban',
  'Bisoprolol',
  'Lisinopril',
  'Losartan',
  'Candesartan',
  'Furosemide',
  'Bendroflumethiazide',
  'Spironolactone',
  'Doxazosin',
  'Tamsulosin',
  'Finasteride',
  'Methotrexate',
  'Hydroxychloroquine',
  'Prednisolone',
  'Fluticasone',
  'Montelukast',
  'Tiotropium',

  // Medical conditions
  'hypertension',
  'hyperlipidemia',
  'hypercholesterolemia',
  'hypothyroidism',
  'hyperthyroidism',
  'diabetes mellitus',
  'prediabetes',
  'atrial fibrillation',
  'heart failure',
  'angina',
  'myocardial infarction',
  'cerebrovascular accident',
  'transient ischaemic attack',
  'peripheral vascular disease',
  'chronic kidney disease',
  'acute kidney injury',
  'asthma',
  'bronchiectasis',
  'pneumonia',
  'pulmonary embolism',
  'deep vein thrombosis',
  'osteoarthritis',
  'rheumatoid arthritis',
  'osteoporosis',
  'fibromyalgia',
  'depression',
  'anxiety',
  'bipolar disorder',
  'schizophrenia',
  'dementia',
  'Parkinson disease',
  'epilepsy',
  'multiple sclerosis',
  'migraine',
  'gastroesophageal reflux',
  'irritable bowel syndrome',
  'inflammatory bowel disease',
  'Crohn disease',
  'ulcerative colitis',
  'coeliac disease',
  'diverticulitis',
  'cholecystitis',
  'hepatitis',
  'cirrhosis',
  'pancreatitis',
  'urinary tract infection',
  'pyelonephritis',
  'benign prostatic hyperplasia',
  'erectile dysfunction',
  'polycystic ovary syndrome',
  'endometriosis',
  'menorrhagia',
  'eczema',
  'psoriasis',
  'cellulitis',
  'shingles',
  'anaemia',
  'thrombocytopenia',
  'lymphoma',
  'leukaemia',
  'myeloma',

  // Lab tests and metrics
  'HbA1c',
  'eGFR',
  'creatinine',
  'urea',
  'electrolytes',
  'full blood count',
  'FBC',
  'liver function tests',
  'LFTs',
  'thyroid function tests',
  'TFTs',
  'lipid profile',
  'cholesterol',
  'triglycerides',
  'HDL',
  'LDL',
  'INR',
  'D-dimer',
  'troponin',
  'BNP',
  'CRP',
  'ESR',
  'PSA',
  'ferritin',
  'B12',
  'folate',
  'vitamin D',
  'calcium',
  'phosphate',
  'magnesium',
  'albumin',
  'bilirubin',
  'ALT',
  'AST',
  'ALP',
  'GGT',
  'amylase',
  'glucose',
  'urinalysis',
  'microscopy',
  'culture',
  'sensitivity',
  'ECG',
  'echocardiogram',
  'chest X-ray',
  'CT scan',
  'MRI',
  'ultrasound',
  'spirometry',
  'peak flow',

  // NHS and ARCP terms
  'ARCP',
  'PDP',
  'CBD',
  'mini-CEX',
  'DOPS',
  'MSF',
  'PSQ',
  'QOF',
  'QI',
  'quality improvement',
  'clinical audit',
  'significant event analysis',
  'SEA',
  'MDT',
  'multidisciplinary team',
  'safeguarding',
  'MARAC',
  'MAPPA',
  'capacity assessment',
  'best interests',
  'DNAR',
  'DNACPR',
  'ReSPECT',
  'advance care planning',
  'palliative care',
  'end of life',
  'two week wait',
  '2WW',
  'urgent referral',
  'routine referral',
  'e-referral',
  'discharge summary',
  'clinic letter',
  'GP summary',
  'SCR',
  'summary care record',

  // Clinical terms
  'differential diagnosis',
  'working diagnosis',
  'red flags',
  'safety netting',
  'shared decision making',
  'informed consent',
  'examination',
  'auscultation',
  'palpation',
  'percussion',
  'inspection',
  'vital signs',
  'observations',
  'blood pressure',
  'pulse',
  'respiratory rate',
  'oxygen saturation',
  'temperature',
  'BMI',
  'ABCDE',
  'NEWS score',
  'NICE guidelines',
  'BNF',
  'MHRA',
  'yellow card',
  'drug interaction',
  'contraindication',
  'side effect',
  'adverse reaction',
  'anaphylaxis',
  'allergy',
  'intolerance',

  // Anatomical terms
  'cardiovascular',
  'respiratory',
  'gastrointestinal',
  'genitourinary',
  'musculoskeletal',
  'neurological',
  'dermatological',
  'endocrine',
  'haematological',
  'immunological',
  'psychiatric',
];

/**
 * Transcription timeout in milliseconds
 * Based on max 5-minute audio + processing buffer
 * AssemblyAI typically processes at ~1 minute audio per 10 seconds
 */
export const TRANSCRIPTION_TIMEOUT_MS = 120_000; // 2 minutes

/**
 * NHS number regex pattern for post-processing fallback
 * Format: XXX XXX XXXX or XXXXXXXXXX
 */
export const NHS_NUMBER_PATTERN = /\b\d{3}\s?\d{3}\s?\d{4}\b/g;
