import { type DraftStatus, type FollowupQuestion } from '@acme/shared';
import { Annotation } from '@langchain/langgraph';

/**
 * Classification alternative returned by the classify node.
 */
export interface ClassificationAlternative {
  entryType: string;
  confidence: number;
  reasoning: string;
}

/**
 * Capability tag extracted from the transcript.
 */
export interface CapabilityTag {
  code: string;
  name: string;
  /** First-person explanation, shown to the user when confirming capabilities. */
  reasoning: string;
  /**
   * Verbatim transcript span evidencing the capability. Guaranteed to be a
   * substring of the transcript — the tag node drops any capability whose quote
   * cannot be found. Persisted as the artefact's capability `evidence`.
   */
  quote: string;
  /**
   * How strongly the capability is demonstrated, graded against its descriptor
   * criteria on the shared ReadinessTier ladder. The tag node only keeps
   * capabilities at `adequate` or above, so a kept tag is never `missing`.
   */
  tier: ReadinessTier;
  /**
   * The trainee's own prose linking their actions to the capability's word
   * descriptor. Distinct from `reasoning` (AI-generated) and `quote`
   * (verbatim evidence). Empty until elicited from the transcript.
   */
  justification?: string;
  /**
   * How well the justification meets the descriptor criteria, on the same
   * ReadinessTier ladder. Drives the readiness card's `justified` flag
   * (`adequate`+ = justified). Undefined until elicited.
   */
  justificationTier?: ReadinessTier;
}

/** Readiness tier for a probe or section against the RCGP descriptors. */
export type ReadinessTier = 'missing' | 'shallow' | 'adequate' | 'strong';

/** Graded readiness of a single probe (Phase 1) or section roll-up (Phase 5). */
export interface ReadinessEntry {
  /** 0–1 score normalised from the depth tier and weight. */
  score: number;
  tier: ReadinessTier;
  /** Whether this unit meets its required threshold. */
  meetsThreshold: boolean;
}

/** Draft lifecycle status, surfaced to the client and gated at save (Phase 6). */
export type { DraftStatus };

/**
 * PDP goal action generated from the reflection.
 */
export interface PdpGoalAction {
  action: string;
  intendedEvidence: string;
}

/**
 * PDP goal generated from the reflection.
 */
export interface PdpGoal {
  goal: string;
  actions: PdpGoalAction[];
}

/**
 * The state that flows through the portfolio processing graph.
 *
 * Each node reads what it needs and returns a partial update.
 * Reducers define how updates are merged (last-write-wins unless specified).
 */
export const PortfolioState = Annotation.Root({
  // ── Identity (set once at graph start, never updated) ──
  conversationId: Annotation<string>,
  artefactId: Annotation<string>,
  userId: Annotation<string>,
  specialty: Annotation<string>,
  trainingStage: Annotation<string>({
    reducer: (_, next) => next,
    default: () => '',
  }),

  // ── Accumulated content ──
  /** All cleaned user messages concatenated — the full transcript */
  fullTranscript: Annotation<string>({
    reducer: (_, next) => next,
    default: () => '',
  }),

  // ── Classification ──
  /** Whether the transcript content is relevant to medical portfolio entries. */
  isRelevant: Annotation<boolean>({
    reducer: (_, next) => next,
    default: () => true,
  }),
  entryType: Annotation<string | null>({
    reducer: (_, next) => next,
    default: () => null,
  }),
  classificationConfidence: Annotation<number>({
    reducer: (_, next) => next,
    default: () => 0,
  }),
  classificationReasoning: Annotation<string>({
    reducer: (_, next) => next,
    default: () => '',
  }),
  alternatives: Annotation<ClassificationAlternative[]>({
    reducer: (_, next) => next,
    default: () => [],
  }),
  /** True once the user has confirmed the entry type. Drives gatherContextRouter. */
  classificationConfirmed: Annotation<boolean>({
    reducer: (_, next) => next,
    default: () => false,
  }),

  /** Number of low-confidence clarification rounds completed. Drives classifyRouter. */
  clarificationRound: Annotation<number>({
    reducer: (_, next) => next,
    default: () => 0,
  }),

  // ── Completeness ──
  missingSections: Annotation<string[]>({
    reducer: (_, next) => next,
    default: () => [],
  }),
  hasEnoughInfo: Annotation<boolean>({
    reducer: (_, next) => next,
    default: () => false,
  }),
  followUpRound: Annotation<number>({
    reducer: (_, next) => next,
    default: () => 0,
  }),
  /**
   * Set when the trainee chooses to stop early (Phase 3). The planner exits the
   * elicitation loop and the entry is saved as `needs_attention` (Phase 6).
   */
  userStopped: Annotation<boolean>({
    reducer: (_, next) => next,
    default: () => false,
  }),
  /** Questions generated by generate_followup, consumed by ask_followup. */
  pendingFollowupQuestions: Annotation<FollowupQuestion[]>({
    reducer: (_, next) => next,
    default: () => [],
  }),
  /**
   * Running history of every follow-up question text asked across all rounds.
   * Appended (not replaced) each round so generate_followup can avoid re-asking.
   */
  askedFollowupQuestions: Annotation<string[]>({
    reducer: (prev, next) => [...prev, ...next],
    default: () => [],
  }),

  // ── Readiness (Phase 1 grades probes; Phase 5 rolls up to sections) ──
  /** Per-probe graded readiness, keyed by probe id. */
  probeReadiness: Annotation<Record<string, ReadinessEntry>>({
    reducer: (_, next) => next,
    default: () => ({}),
  }),
  /** Per-output-section readiness roll-up, keyed by section id. */
  sectionReadiness: Annotation<Record<string, ReadinessEntry>>({
    reducer: (_, next) => next,
    default: () => ({}),
  }),
  /** Overall readiness score 0–10, shown on the Entry Card. */
  readinessScore: Annotation<number>({
    reducer: (_, next) => next,
    default: () => 0,
  }),
  /** Draft lifecycle status, gated at save. */
  draftStatus: Annotation<DraftStatus>({
    reducer: (_, next) => next,
    default: () => 'in_progress',
  }),

  // ── Capabilities ──
  capabilities: Annotation<CapabilityTag[]>({
    reducer: (_, next) => next,
    default: () => [],
  }),

  // ── Reflection ──
  title: Annotation<string | null>({
    reducer: (_, next) => next,
    default: () => null,
  }),
  reflection: Annotation<Array<{
    sectionId: string;
    title: string;
    text: string;
    covered: boolean;
  }> | null>({
    reducer: (_, next) => next,
    default: () => null,
  }),
  /**
   * The reflection projected into the output document fields (Phase 4).
   * Derived deterministically from `reflection` by `composeDocument`; this is
   * the shape the trainee submits (e.g. the FourteenFish "Brief description").
   */
  composedDocument: Annotation<
    Array<{
      sectionId: string;
      label: string;
      text: string;
    }>
  >({
    reducer: (_, next) => next,
    default: () => [],
  }),

  // ── PDP ──
  pdpGoals: Annotation<PdpGoal[]>({
    reducer: (_, next) => next,
    default: () => [],
  }),
});

/** Inferred type of the graph state */
export type PortfolioStateType = typeof PortfolioState.State;
